export const ROL_PLANEACION = 'PLANEACION';
export const ROL_JEFE_DEPENDENCIA_PLANEACION = 'JEFE_DEPENDENCIA_PLANEACION';
export const ROL_JEFE_DEPENDENCIA = 'JEFE_DEPENDENCIA';
export const ROL_ASISTENTE_DEPENDENCIA = 'ASISTENTE_DEPENDENCIA';